export const SET_THEME_PALETTE_TYPE = 'SET_THEME_PALETTE_TYPE'
export const SET_PRIMARY_COLOR = 'SET_PRIMARY_COLOR'
export const SET_SECONDARY_COLOR = 'SET_SECONDARY_COLOR'
export const SET_ERROR_COLOR = 'SET_ERROR_COLOR'
